variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
               -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
               -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
               -Dmaven.repo.local=/cache/maven.repository"

stages:
- test
- pack
- docker

test:api:
  stage: test
  image: maven:3.3.9-jdk-8-alpine
  script:
  - mvn clean validate compile test -B

pack:api:
  stage: pack
  image: maven:3.3.9-jdk-8-alpine
  script:
  - mvn clean install -B -DskipTests
  artifacts:
    paths:
    - ./target/*.war

docker:api-master:
  stage: docker
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
  - master

docker:api-tag:
  stage: docker
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
  - master