variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"

cache:
  cache:
  untracked: true
  paths:
    - /root/.m2/repository/

stages:
- test

test:api:
  stage: test
  image: maven:3.3.9-jdk-8-alpine
  script:
  - mvn clean validate compile test -B